apiVersion: v1
kind: Service
metadata:
  name: minecraft-lb
  namespace: default
  labels:
    app: minecraft
spec:
  type: LoadBalancer
  selector:
    app: minecraft
  ports:
    - port: 25565
      targetPort: 25565
      protocol: TCP
      name: game
    - port: 9225      # Porta de m√©tricas
      targetPort: 9225
      protocol: TCP
      name: metrics